<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import { RouterLink, useRoute, useRouter } from 'vue-router'
import { ArrowLeft, Edit3, Mail, MapPin, Phone, Plus, Search, Trash2, UserRoundX } from 'lucide-vue-next'
import { UiBadge, UiButton, UiCard, UiEmptyState, UiInput, UiModal, UiPagination, UiSelect, UiTable, UiToast } from '@/components/ui'
import { mockCustomerPurchases, mockCustomers } from '@/data/sales'
import type { Customer, CustomerType, PaymentStatus } from '@/types/sales'
import type { StatusTone } from '@/types/ui'
import { useLocale } from '@/composables/useLocale'

type FormMode = 'add' | 'edit'
type ConfirmAction = 'deactivate' | 'delete'
interface CustomerForm { name: string; type: CustomerType; phone: string; email: string; address: string; contactPerson: string; notes: string; active: boolean }
const { t, formatCurrency, formatDate, formatNumber } = useLocale()
const route = useRoute(); const router = useRouter()
const customers = ref<Customer[]>(mockCustomers.map((item) => ({ ...item })))
const search = ref(''); const typeFilter = ref('all'); const statusFilter = ref('all'); const currentPage = ref(1); const pageSize = ref(10)
const modalOpen = ref(false); const confirmOpen = ref(false); const formMode = ref<FormMode>('add'); const confirmAction = ref<ConfirmAction>('deactivate')
const selected = ref<Customer | null>(null); const formError = ref(''); const toast = ref<{ title: string; description: string; tone: StatusTone } | null>(null)
const form = reactive<CustomerForm>({ name: '', type: 'Individual', phone: '', email: '', address: '', contactPerson: '', notes: '', active: true })
const types: CustomerType[] = ['Individual', 'Fruit Store', 'Restaurant', 'Distributor', 'Supermarket', 'Other']
const typeKey = (type: CustomerType) => ({ Individual: 'individual', 'Fruit Store': 'fruitStore', Restaurant: 'restaurant', Distributor: 'distributor', Supermarket: 'supermarket', Other: 'other' }[type])
const typeLabel = (type: CustomerType) => t(`customersPage.types.${typeKey(type)}`)
const typeOptions = computed(() => [{ label: t('customersPage.filters.allTypes'), value: 'all' }, ...types.map((type) => ({ label: typeLabel(type), value: type }))])
const formTypeOptions = computed(() => types.map((type) => ({ label: typeLabel(type), value: type })))
const statusOptions = computed(() => [{ label: t('customersPage.filters.allStatuses'), value: 'all' }, { label: t('customersPage.status.active'), value: 'active' }, { label: t('customersPage.status.inactive'), value: 'inactive' }])
const detail = computed(() => customers.value.find((item) => item.id === route.params.customerId))
const filtered = computed(() => { const query = search.value.trim().toLowerCase(); return customers.value.filter((item) => (!query || `${item.id} ${item.name} ${item.phone} ${item.email}`.toLowerCase().includes(query)) && (typeFilter.value === 'all' || item.type === typeFilter.value) && (statusFilter.value === 'all' || item.active === (statusFilter.value === 'active'))).sort((a, b) => b.totalTransactions - a.totalTransactions) })
const paginated = computed(() => filtered.value.slice((currentPage.value - 1) * pageSize.value, currentPage.value * pageSize.value))
const history = computed(() => mockCustomerPurchases.filter((item) => item.customerId === detail.value?.id))
const paymentTone: Record<PaymentStatus, StatusTone> = { Paid: 'success', Partial: 'warning', Unpaid: 'danger' }
const paymentLabel = (status: PaymentStatus) => t(`salesPage.paymentStatus.${status.toLowerCase()}`)
function resetForm() { Object.assign(form, { name: '', type: 'Individual', phone: '', email: '', address: '', contactPerson: '', notes: '', active: true }); formError.value = '' }
function openAdd() { resetForm(); formMode.value = 'add'; selected.value = null; modalOpen.value = true }
function openEdit(item: Customer) { selected.value = item; Object.assign(form, { name: item.name, type: item.type, phone: item.phone, email: item.email, address: item.address, contactPerson: item.contactPerson, notes: item.notes, active: item.active }); formMode.value = 'edit'; formError.value = ''; modalOpen.value = true }
function notify(title: string, description: string, tone: StatusTone = 'success') { toast.value = { title, description, tone }; window.setTimeout(() => { toast.value = null }, 4000) }
function save() { if (!form.name.trim() || !form.phone.trim() || !form.email.trim() || !form.address.trim()) { formError.value = t('customersPage.validation.required'); return } const values = { ...form, name: form.name.trim(), email: form.email.trim().toLowerCase() }; if (formMode.value === 'edit' && selected.value) { Object.assign(selected.value, values); notify(t('customersPage.toast.updated'), t('customersPage.toast.updatedDescription', { name: values.name })) } else { const id = `CUS-${String(customers.value.length + 1).padStart(4, '0')}`; customers.value.unshift({ id, ...values, totalTransactions: 0, totalPurchase: 0, outstandingPayment: 0, lastPurchase: '' }); notify(t('customersPage.toast.added'), t('customersPage.toast.addedDescription', { name: values.name })) } modalOpen.value = false }
function ask(item: Customer, action: ConfirmAction) { selected.value = item; confirmAction.value = action; confirmOpen.value = true }
function confirmActionNow() { if (!selected.value) return; const item = selected.value; if (confirmAction.value === 'deactivate') { item.active = false; notify(t('customersPage.toast.deactivated'), t('customersPage.toast.deactivatedDescription', { name: item.name }), 'warning') } else { customers.value = customers.value.filter((customer) => customer.id !== item.id); if (route.params.customerId) void router.push('/customers'); notify(t('customersPage.toast.deleted'), t('customersPage.toast.deletedDescription', { name: item.name })) } confirmOpen.value = false }
watch([search, typeFilter, statusFilter], () => { currentPage.value = 1 })
</script>

<template><div class="@container">
  <template v-if="detail">
    <header class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><RouterLink to="/customers" class="mb-3 inline-flex items-center gap-1.5 text-sm font-medium text-green-700"><ArrowLeft :size="16" />{{ t('customersPage.back') }}</RouterLink><div class="flex flex-wrap items-center gap-3"><h1 class="page-title">{{ detail.name }}</h1><UiBadge :tone="detail.active ? 'success' : 'neutral'">{{ t(detail.active ? 'customersPage.status.active' : 'customersPage.status.inactive') }}</UiBadge><UiBadge v-if="detail.totalTransactions >= 10" tone="info">{{ t('customersPage.recurring') }}</UiBadge></div><p class="secondary-text mt-2">{{ detail.id }} · {{ typeLabel(detail.type) }}</p></div><div class="flex flex-wrap gap-2"><UiButton variant="secondary" @click="openEdit(detail)"><template #leading><Edit3 :size="16" /></template>{{ t('common.edit') }}</UiButton><UiButton v-if="detail.active" variant="secondary" @click="ask(detail, 'deactivate')"><template #leading><UserRoundX :size="16" /></template>{{ t('customersPage.deactivate') }}</UiButton><UiButton variant="danger" @click="ask(detail, 'delete')"><template #leading><Trash2 :size="16" /></template>{{ t('common.delete') }}</UiButton></div></header>
    <section class="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div v-for="item in [{ label: t('customersPage.fields.totalPurchase'), value: formatCurrency(detail.totalPurchase) }, { label: t('customersPage.fields.totalTransactions'), value: formatNumber(detail.totalTransactions) }, { label: t('customersPage.detail.outstanding'), value: formatCurrency(detail.outstandingPayment) }, { label: t('customersPage.detail.lastTransaction'), value: detail.lastPurchase ? formatDate(detail.lastPurchase) : '—' }]" :key="item.label" class="ui-card p-5"><p class="text-sm text-slate-500">{{ item.label }}</p><p class="mt-3 text-xl font-semibold">{{ item.value }}</p></div></section>
    <UiCard class="mt-6" :title="t('customersPage.detail.information')"><div class="grid gap-5 sm:grid-cols-2 xl:grid-cols-3"><div><p class="ui-label">{{ t('customersPage.fields.contactPerson') }}</p><p class="mt-1">{{ detail.contactPerson || '—' }}</p></div><div><p class="ui-label">{{ t('customersPage.fields.phone') }}</p><p class="mt-1 flex gap-2"><Phone :size="15" />{{ detail.phone }}</p></div><div><p class="ui-label">{{ t('customersPage.fields.email') }}</p><p class="mt-1 flex gap-2"><Mail :size="15" />{{ detail.email }}</p></div><div class="sm:col-span-2"><p class="ui-label">{{ t('customersPage.fields.address') }}</p><p class="mt-1 flex gap-2"><MapPin :size="15" class="shrink-0" />{{ detail.address }}</p></div><div><p class="ui-label">{{ t('customersPage.fields.notes') }}</p><p class="mt-1">{{ detail.notes || '—' }}</p></div></div></UiCard>
    <section class="mt-6"><h2 class="section-title mb-4">{{ t('customersPage.detail.purchaseHistory') }}</h2><UiEmptyState v-if="!history.length" :title="t('customersPage.detail.noHistory')" :description="t('customersPage.detail.noHistoryDescription')" /><UiTable v-else :caption="t('customersPage.detail.purchaseHistory')"><template #head><tr><th>{{ t('customersPage.history.invoice') }}</th><th>{{ t('customersPage.history.date') }}</th><th>{{ t('customersPage.history.products') }}</th><th>{{ t('customersPage.history.weight') }}</th><th>{{ t('customersPage.history.total') }}</th><th>{{ t('customersPage.history.payment') }}</th></tr></template><tr v-for="item in history" :key="item.id"><td class="font-medium text-green-700">{{ item.invoiceNumber }}</td><td>{{ formatDate(item.date) }}</td><td>{{ item.products }}</td><td>{{ formatNumber(item.weightKg) }} {{ t('common.kg') }}</td><td>{{ formatCurrency(item.total) }}</td><td><UiBadge :tone="paymentTone[item.paymentStatus]">{{ paymentLabel(item.paymentStatus) }}</UiBadge></td></tr></UiTable></section>
  </template>
  <template v-else>
    <header class="flex flex-col gap-5 sm:flex-row sm:justify-between"><div><h1 class="page-title">{{ t('customersPage.title') }}</h1><p class="secondary-text mt-2">{{ t('customersPage.description') }}</p></div><UiButton class="self-start" @click="openAdd"><template #leading><Plus :size="18" /></template>{{ t('customersPage.add') }}</UiButton></header>
    <section class="mt-8"><div class="mb-5 grid gap-3 sm:grid-cols-3"><UiInput v-model="search" :label="t('common.search')" type="search" :placeholder="t('customersPage.filters.searchPlaceholder')"><template #trailing><Search :size="17" /></template></UiInput><UiSelect v-model="typeFilter" :label="t('customersPage.fields.type')" :options="typeOptions" /><UiSelect v-model="statusFilter" :label="t('customersPage.fields.status')" :options="statusOptions" /></div><UiEmptyState v-if="!filtered.length" :title="t('customersPage.empty.title')" :description="t('customersPage.empty.description')" /><template v-else><UiTable :caption="t('customersPage.listLabel')"><template #head><tr><th>{{ t('common.number') }}</th><th>{{ t('customersPage.fields.name') }}</th><th>{{ t('customersPage.fields.type') }}</th><th>{{ t('customersPage.fields.phone') }}</th><th>{{ t('customersPage.fields.totalTransactions') }}</th><th>{{ t('customersPage.fields.totalPurchase') }}</th><th>{{ t('customersPage.fields.lastPurchase') }}</th><th>{{ t('customersPage.fields.status') }}</th><th><span class="sr-only">{{ t('common.actions') }}</span></th></tr></template><tr v-for="(item, index) in paginated" :key="item.id" class="cursor-pointer transition-colors hover:bg-green-50/50" tabindex="0" @click="router.push(`/customers/${item.id}`)" @keydown.enter="router.push(`/customers/${item.id}`)"><td class="text-slate-500">{{ (currentPage - 1) * pageSize + index + 1 }}</td><td><p class="font-medium text-green-700">{{ item.name }}</p><UiBadge v-if="item.totalTransactions >= 10" tone="info">{{ t('customersPage.recurring') }}</UiBadge></td><td>{{ typeLabel(item.type) }}</td><td>{{ item.phone }}</td><td>{{ formatNumber(item.totalTransactions) }}</td><td>{{ formatCurrency(item.totalPurchase) }}</td><td>{{ item.lastPurchase ? formatDate(item.lastPurchase) : '—' }}</td><td><UiBadge :tone="item.active ? 'success' : 'neutral'">{{ t(item.active ? 'customersPage.status.active' : 'customersPage.status.inactive') }}</UiBadge></td><td><div class="flex"><button class="rounded-md p-2 text-slate-500" :aria-label="t('common.edit')" @click.stop="openEdit(item)"><Edit3 :size="16" /></button><button v-if="item.active" class="rounded-md p-2 text-amber-700" :aria-label="t('customersPage.deactivate')" @click.stop="ask(item, 'deactivate')"><UserRoundX :size="16" /></button></div></td></tr></UiTable><UiPagination v-model:page="currentPage" v-model:page-size="pageSize" :total="filtered.length" /></template></section>
  </template>
  <UiModal v-model="modalOpen" :title="t(formMode === 'add' ? 'customersPage.modal.addTitle' : 'customersPage.modal.editTitle')"><form id="customer-form" class="space-y-4" @submit.prevent="save"><UiInput v-model="form.name" :label="t('customersPage.fields.name')" required /><UiSelect v-model="form.type" :label="t('customersPage.fields.type')" :options="formTypeOptions" /><div class="grid gap-4 sm:grid-cols-2"><UiInput v-model="form.phone" :label="t('customersPage.fields.phone')" type="tel" required /><UiInput v-model="form.email" :label="t('customersPage.fields.email')" type="email" required /></div><UiInput v-model="form.address" :label="t('customersPage.fields.address')" required /><UiInput v-model="form.contactPerson" :label="t('customersPage.fields.contactPerson')" /><div><label class="ui-label" for="customer-notes">{{ t('customersPage.fields.notes') }}</label><textarea id="customer-notes" v-model="form.notes" class="ui-field mt-1.5 min-h-24" /></div><label class="flex gap-2 text-sm"><input v-model="form.active" type="checkbox" />{{ t('customersPage.modal.activeCustomer') }}</label><p v-if="formError" class="text-sm text-red-700">{{ formError }}</p></form><template #footer><UiButton variant="secondary" @click="modalOpen = false">{{ t('common.cancel') }}</UiButton><UiButton type="submit" form="customer-form">{{ t(formMode === 'add' ? 'customersPage.add' : 'common.save') }}</UiButton></template></UiModal>
  <UiModal v-model="confirmOpen" :title="t(confirmAction === 'delete' ? 'customersPage.confirm.deleteTitle' : 'customersPage.confirm.deactivateTitle')" :description="t(confirmAction === 'delete' ? 'customersPage.confirm.deleteDescription' : 'customersPage.confirm.deactivateDescription', { name: selected?.name })"><template #footer><UiButton variant="secondary" @click="confirmOpen = false">{{ t('common.cancel') }}</UiButton><UiButton :variant="confirmAction === 'delete' ? 'danger' : 'primary'" @click="confirmActionNow">{{ t(confirmAction === 'delete' ? 'common.delete' : 'customersPage.deactivate') }}</UiButton></template></UiModal>
  <div v-if="toast" class="fixed right-4 bottom-4 z-50"><UiToast v-bind="toast" @dismiss="toast = null" /></div>
</div></template>
