<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { RouterLink, useRoute, useRouter } from 'vue-router'
import { ArrowLeft, Banknote, Edit3, Printer, RefreshCw, XCircle } from 'lucide-vue-next'
import { UiBadge, UiButton, UiCard, UiEmptyState, UiInput, UiModal, UiSelect, UiTable, UiToast } from '@/components/ui'
import { mockCustomers, mockSaleDetails } from '@/data/sales'
import type { OrderStatus, PaymentMethod, PaymentStatus, SaleTransactionDetail } from '@/types/sales'
import type { StatusTone } from '@/types/ui'
import { useLocale } from '@/composables/useLocale'

const { t, formatCurrency, formatDate, formatNumber } = useLocale()
const route = useRoute(); const router = useRouter()
const transaction = ref<SaleTransactionDetail | null>(null)
const source = mockSaleDetails.find((item) => item.id === route.params.id)
if (source) transaction.value = { ...source, products: source.products.map((item) => ({ ...item })), payments: source.payments.map((item) => ({ ...item })) }
const customer = computed(() => mockCustomers.find((item) => item.id === transaction.value?.customerId))
const outstanding = computed(() => Math.max(0, (transaction.value?.grandTotal ?? 0) - (transaction.value?.amountPaid ?? 0)))
const paymentOpen = ref(false); const statusOpen = ref(false); const cancelOpen = ref(false); const paymentError = ref('')
const toast = ref<{ title: string; description: string; tone: StatusTone } | null>(null)
const paymentForm = reactive<{ date: string; method: PaymentMethod; amount: number }>({ date: '2026-09-18', method: 'Bank Transfer', amount: 0 })
const nextOrderStatus = ref<OrderStatus>('Confirmed')
const paymentTone: Record<PaymentStatus, StatusTone> = { Paid: 'success', Partial: 'warning', Unpaid: 'danger' }
const orderTone: Record<OrderStatus, StatusTone> = { Draft: 'neutral', Confirmed: 'info', Processing: 'warning', Ready: 'success', Delivered: 'success', Cancelled: 'danger' }
const paymentLabel = (value: PaymentStatus) => t(`salesPage.paymentStatus.${value.toLowerCase()}`)
const orderLabel = (value: OrderStatus) => t(`salesPage.orderStatus.${value.toLowerCase()}`)
const methodKey = (value: PaymentMethod) => value === 'Bank Transfer' ? 'bankTransfer' : value.toLowerCase()
const methodLabel = (value: PaymentMethod) => t(`newSale.paymentMethods.${methodKey(value)}`)
const deliveryKey = computed(() => transaction.value?.deliveryMethod === 'Customer Pickup' ? 'pickup' : transaction.value?.deliveryMethod === 'Farm Delivery' ? 'farm' : 'thirdParty')
const methodOptions = computed(() => (['Cash', 'Bank Transfer', 'Other'] as PaymentMethod[]).map((value) => ({ label: methodLabel(value), value })))
const orderOptions = computed(() => (['Draft', 'Confirmed', 'Processing', 'Ready', 'Delivered', 'Cancelled'] as OrderStatus[]).map((value) => ({ label: orderLabel(value), value })))
function notify(title: string, description: string, tone: StatusTone = 'success') { toast.value = { title, description, tone }; window.setTimeout(() => { toast.value = null }, 4000) }
function openPayment() { paymentForm.amount = outstanding.value; paymentError.value = ''; paymentOpen.value = true }
function recordPayment() { if (!transaction.value || !Number.isFinite(Number(paymentForm.amount)) || Number(paymentForm.amount) <= 0) { paymentError.value = t('saleDetail.validation.payment'); return } const amount = Math.round(Number(paymentForm.amount)); transaction.value.payments.push({ id: `PAY-${String(transaction.value.payments.length + 1).padStart(4, '0')}`, date: paymentForm.date, method: paymentForm.method, amount }); transaction.value.amountPaid += amount; transaction.value.paymentStatus = transaction.value.amountPaid >= transaction.value.grandTotal ? 'Paid' : 'Partial'; paymentOpen.value = false; notify(t('saleDetail.toast.paymentTitle'), t('saleDetail.toast.paymentDescription', { amount: formatCurrency(amount) })) }
function updateStatus() { if (!transaction.value) return; transaction.value.orderStatus = nextOrderStatus.value; statusOpen.value = false; notify(t('saleDetail.toast.statusTitle'), t('saleDetail.toast.statusDescription', { status: orderLabel(nextOrderStatus.value) })) }
function openStatus() { if (!transaction.value) return; nextOrderStatus.value = transaction.value.orderStatus; statusOpen.value = true }
function cancelTransaction() { if (!transaction.value) return; transaction.value.orderStatus = 'Cancelled'; cancelOpen.value = false; notify(t('saleDetail.toast.cancelTitle'), t('saleDetail.toast.cancelDescription'), 'warning') }
function printInvoice() { window.print() }
</script>

<template><div class="@container invoice-page">
  <UiEmptyState v-if="!transaction" :title="t('saleDetail.notFound.title')" :description="t('saleDetail.notFound.description')"><UiButton @click="router.push('/sales')">{{ t('saleDetail.back') }}</UiButton></UiEmptyState>
  <template v-else>
    <header class="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><RouterLink to="/sales" class="no-print mb-3 inline-flex items-center gap-1.5 text-sm font-medium text-green-700"><ArrowLeft :size="16" />{{ t('saleDetail.back') }}</RouterLink><p class="text-xs font-semibold uppercase tracking-widest text-green-700">{{ t('saleDetail.invoice') }}</p><h1 class="page-title mt-1">{{ transaction.invoiceNumber }}</h1><p class="secondary-text mt-2">{{ formatDate(transaction.saleDate) }} · {{ customer?.name }}</p></div><div class="no-print flex flex-wrap gap-2"><UiButton variant="secondary" @click="router.push({ path: '/sales/new', query: { edit: transaction.id } })"><template #leading><Edit3 :size="16" /></template>{{ t('saleDetail.actions.edit') }}</UiButton><UiButton variant="secondary" :disabled="transaction.paymentStatus === 'Paid'" @click="openPayment"><template #leading><Banknote :size="16" /></template>{{ t('saleDetail.actions.payment') }}</UiButton><UiButton variant="secondary" @click="openStatus"><template #leading><RefreshCw :size="16" /></template>{{ t('saleDetail.actions.status') }}</UiButton><UiButton variant="secondary" @click="printInvoice"><template #leading><Printer :size="16" /></template>{{ t('saleDetail.actions.print') }}</UiButton><UiButton variant="danger" :disabled="transaction.orderStatus === 'Cancelled'" @click="cancelOpen = true"><template #leading><XCircle :size="16" /></template>{{ t('saleDetail.actions.cancel') }}</UiButton></div></header>

    <section class="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><div class="ui-card p-5"><p class="text-sm text-slate-500">{{ t('saleDetail.fields.invoice') }}</p><p class="mt-2 font-semibold">{{ transaction.invoiceNumber }}</p></div><div class="ui-card p-5"><p class="text-sm text-slate-500">{{ t('saleDetail.fields.date') }}</p><p class="mt-2 font-semibold">{{ formatDate(transaction.saleDate) }}</p></div><div class="ui-card p-5"><p class="text-sm text-slate-500">{{ t('saleDetail.fields.customer') }}</p><p class="mt-2 font-semibold">{{ customer?.name }}</p></div><div class="ui-card p-5"><p class="text-sm text-slate-500">{{ t('saleDetail.fields.paymentStatus') }}</p><UiBadge class="mt-2" :tone="paymentTone[transaction.paymentStatus]">{{ paymentLabel(transaction.paymentStatus) }}</UiBadge></div><div class="ui-card p-5"><p class="text-sm text-slate-500">{{ t('saleDetail.fields.orderStatus') }}</p><UiBadge class="mt-2" :tone="orderTone[transaction.orderStatus]">{{ orderLabel(transaction.orderStatus) }}</UiBadge></div></section>

    <section class="mt-6"><h2 class="section-title mb-4">{{ t('saleDetail.sections.products') }}</h2><UiTable :caption="t('saleDetail.sections.products')"><template #head><tr><th>{{ t('saleDetail.products.variety') }}</th><th>{{ t('saleDetail.products.grade') }}</th><th class="numeric">{{ t('saleDetail.products.quantity') }}</th><th class="numeric">{{ t('saleDetail.products.price') }}</th><th class="numeric">{{ t('saleDetail.products.discount') }}</th><th class="numeric">{{ t('saleDetail.products.subtotal') }}</th></tr></template><tr v-for="item in transaction.products" :key="item.id"><td class="font-medium">{{ item.variety }}</td><td><UiBadge>{{ item.grade }}</UiBadge></td><td class="numeric">{{ formatNumber(item.quantity) }} {{ item.unit }}</td><td class="numeric">{{ formatCurrency(item.pricePerUnit) }}/{{ item.unit }}</td><td class="numeric">{{ formatCurrency(item.discount) }}</td><td class="numeric font-semibold">{{ formatCurrency(item.subtotal) }}</td></tr></UiTable></section>

    <div class="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(20rem,0.65fr)]"><div class="space-y-6"><UiCard :title="t('saleDetail.sections.customer')"><dl class="grid gap-5 sm:grid-cols-3"><div><dt class="ui-label">{{ t('saleDetail.customer.name') }}</dt><dd class="mt-1 font-medium">{{ customer?.name }}</dd></div><div><dt class="ui-label">{{ t('saleDetail.customer.phone') }}</dt><dd class="mt-1">{{ customer?.phone }}</dd></div><div><dt class="ui-label">{{ t('saleDetail.customer.address') }}</dt><dd class="mt-1">{{ customer?.address }}</dd></div></dl></UiCard><UiCard :title="t('saleDetail.sections.delivery')"><dl class="grid gap-5 sm:grid-cols-3"><div><dt class="ui-label">{{ t('saleDetail.delivery.method') }}</dt><dd class="mt-1">{{ t(`newSale.deliveryMethods.${deliveryKey}`) }}</dd></div><div><dt class="ui-label">{{ t('saleDetail.delivery.date') }}</dt><dd class="mt-1">{{ formatDate(transaction.deliveryDate) }}</dd></div><div><dt class="ui-label">{{ t('saleDetail.delivery.address') }}</dt><dd class="mt-1">{{ transaction.deliveryAddress || '—' }}</dd></div></dl></UiCard></div>
      <UiCard :title="t('saleDetail.sections.summary')"><dl class="space-y-3 text-sm"><div class="flex justify-between"><dt class="text-slate-500">{{ t('saleDetail.summary.subtotal') }}</dt><dd>{{ formatCurrency(transaction.subtotal) }}</dd></div><div class="flex justify-between"><dt class="text-slate-500">{{ t('saleDetail.summary.discount') }}</dt><dd>- {{ formatCurrency(transaction.discount) }}</dd></div><div class="flex justify-between"><dt class="text-slate-500">{{ t('saleDetail.summary.delivery') }}</dt><dd>{{ formatCurrency(transaction.deliveryCost) }}</dd></div><div class="flex justify-between border-t border-slate-200 pt-3 text-base font-semibold"><dt>{{ t('saleDetail.summary.grandTotal') }}</dt><dd class="text-green-700">{{ formatCurrency(transaction.grandTotal) }}</dd></div><div class="flex justify-between"><dt class="text-slate-500">{{ t('saleDetail.summary.paid') }}</dt><dd>{{ formatCurrency(transaction.amountPaid) }}</dd></div><div class="flex justify-between text-base font-semibold"><dt>{{ t('saleDetail.summary.outstanding') }}</dt><dd :class="outstanding ? 'text-amber-700' : 'text-green-700'">{{ formatCurrency(outstanding) }}</dd></div></dl></UiCard></div>

    <section class="mt-6"><div class="mb-4 flex items-center justify-between"><h2 class="section-title">{{ t('saleDetail.sections.payment') }}</h2><UiButton v-if="transaction.paymentStatus !== 'Paid'" class="no-print" size="sm" @click="openPayment">{{ t('saleDetail.actions.payment') }}</UiButton></div><UiEmptyState v-if="!transaction.payments.length" :title="t('saleDetail.payment.empty')" :description="t('saleDetail.payment.emptyDescription')" /><UiTable v-else :caption="t('saleDetail.sections.payment')"><template #head><tr><th>{{ t('saleDetail.payment.date') }}</th><th>{{ t('saleDetail.payment.method') }}</th><th class="numeric">{{ t('saleDetail.payment.amount') }}</th></tr></template><tr v-for="item in transaction.payments" :key="item.id"><td>{{ formatDate(item.date) }}</td><td>{{ methodLabel(item.method) }}</td><td class="numeric font-semibold">{{ formatCurrency(item.amount) }}</td></tr></UiTable></section>
  </template>

  <UiModal v-model="paymentOpen" :title="t('saleDetail.payment.modalTitle')" :description="t('saleDetail.payment.modalDescription', { amount: formatCurrency(outstanding) })"><div class="space-y-4"><UiInput v-model="paymentForm.date" :label="t('saleDetail.payment.date')" type="date" /><UiSelect v-model="paymentForm.method" :label="t('saleDetail.payment.method')" :options="methodOptions" /><UiInput v-model="paymentForm.amount" :label="t('saleDetail.payment.amount')" type="number" min="1" step="1" :error="paymentError" /></div><template #footer><UiButton variant="secondary" @click="paymentOpen = false">{{ t('common.cancel') }}</UiButton><UiButton @click="recordPayment">{{ t('saleDetail.payment.record') }}</UiButton></template></UiModal>
  <UiModal v-model="statusOpen" :title="t('saleDetail.status.modalTitle')"><UiSelect v-model="nextOrderStatus" :label="t('saleDetail.fields.orderStatus')" :options="orderOptions" /><template #footer><UiButton variant="secondary" @click="statusOpen = false">{{ t('common.cancel') }}</UiButton><UiButton @click="updateStatus">{{ t('common.save') }}</UiButton></template></UiModal>
  <UiModal v-model="cancelOpen" :title="t('saleDetail.cancel.title')" :description="t('saleDetail.cancel.description')"><template #footer><UiButton variant="secondary" @click="cancelOpen = false">{{ t('common.back') }}</UiButton><UiButton variant="danger" @click="cancelTransaction">{{ t('saleDetail.actions.cancel') }}</UiButton></template></UiModal>
  <div v-if="toast" class="no-print fixed right-4 bottom-4 z-50"><UiToast v-bind="toast" @dismiss="toast = null" /></div>
</div></template>

<style scoped>@media print { .no-print { display: none !important; } .invoice-page { color: #0f172a; } }</style>
