<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, reactive, ref, watch } from 'vue'
import { onBeforeRouteLeave, useRouter } from 'vue-router'
import { Bell, Eye, EyeOff, LandPlot, LockKeyhole, Save, Settings2, ShoppingCart, UserRound } from 'lucide-vue-next'
import { z } from 'zod'
import { UiBadge, UiButton, UiCard, UiInput, UiModal, UiSelect, UiToast } from '@/components/ui'
import { mockFarms } from '@/data/farms'
import { useAuthStore } from '@/stores/auth'
import { defaultPreferences, useSettingsStore } from '@/stores/settings'
import type { AppSettings, SettingsSection } from '@/types/settings'
import { useLocale } from '@/composables/useLocale'

const { t, formatNumber } = useLocale(); const router = useRouter(); const auth = useAuthStore(); const store = useSettingsStore()
function cloneSettings(value: AppSettings): AppSettings { return JSON.parse(JSON.stringify(value)) as AppSettings }
const draft = reactive<AppSettings>(cloneSettings(store.settings))
const active = ref<SettingsSection>('profile'); const saving = ref(false); const resetOpen = ref(false); const logoutOpen = ref(false)
const toast = ref<{ title: string; description?: string; tone: 'success' | 'info' | 'danger' } | null>(null)
const errors = ref<Record<string, string>>({}); const photoInput = ref<HTMLInputElement>()
const password = reactive({ current: '', next: '', confirm: '' }); const showCurrent = ref(false); const showNext = ref(false); const showConfirm = ref(false); const passwordError = ref('')
const isOwner = computed(() => auth.user?.role === 'OWNER')
const baseline = ref(JSON.stringify(store.settings)); const dirty = computed(() => JSON.stringify(draft) !== baseline.value)
const sections = computed(() => ([
  { id: 'profile', icon: UserRound }, { id: 'preferences', icon: Settings2 },
  ...(isOwner.value ? [{ id: 'farm', icon: LandPlot }, { id: 'sales', icon: ShoppingCart }] : []),
  { id: 'notifications', icon: Bell }, { id: 'security', icon: LockKeyhole },
] as { id: SettingsSection; icon: typeof UserRound }[]))
const languageOptions = computed(() => [{ label: t('common.indonesia'), value: 'id' }, { label: t('common.english'), value: 'en' }])
const dateOptions = [{ label: 'DD/MM/YYYY', value: 'DD/MM/YYYY' }, { label: 'DD MMM YYYY', value: 'DD MMM YYYY' }]
const weightOptions = computed(() => [{ label: t('settings.preferences.kilogram'), value: 'kg' }, { label: t('settings.preferences.ton'), value: 'ton' }])
const areaOptions = computed(() => [{ label: t('settings.preferences.hectare'), value: 'ha' }, { label: t('settings.preferences.squareMeter'), value: 'm2' }])
const themeOptions = computed(() => ['light', 'dark', 'system'].map((value) => ({ label: t(`settings.preferences.themes.${value}`), value })))
const farmOptions = mockFarms.map((item) => ({ label: item.name, value: item.id })); const varietyOptions = ['Hass', 'Fuerte', 'Miki', 'Reed'].map((value) => ({ label: value, value }))
const paymentMethodOptions = computed(() => [{ label: t('newSale.paymentMethods.cash'), value: 'Cash' }, { label: t('newSale.paymentMethods.bankTransfer'), value: 'Bank Transfer' }, { label: t('newSale.paymentMethods.other'), value: 'Other' }])
const paymentStatusOptions = computed(() => [{ label: t('salesPage.paymentStatus.paid'), value: 'Paid' }, { label: t('salesPage.paymentStatus.unpaid'), value: 'Unpaid' }])
const deliveryOptions = computed(() => [{ label: t('newSale.deliveryMethods.pickup'), value: 'Customer Pickup' }, { label: t('newSale.deliveryMethods.farm'), value: 'Farm Delivery' }, { label: t('newSale.deliveryMethods.thirdParty'), value: 'Third Party Delivery' }])
const notificationGroups = computed(() => [
  { id: 'activities', items: ['activityDue', 'activityOverdue', 'activityCompleted'] }, { id: 'harvest', items: ['harvestRecorded', 'harvestTarget'] },
  { id: 'stock', items: ['salesStockLow', 'inventoryStockLow', 'stockOut'] }, { id: 'sales', items: ['saleRecorded', 'paymentReceived', 'paymentOutstanding', 'orderStatusChanged'] },
] as const)
const invoicePreview = computed(() => `${draft.sales.invoicePrefix || 'INV'}-2026-0001`)
const passwordStrength = computed(() => password.next.length >= 12 ? 'strong' : password.next.length >= 8 ? 'medium' : 'weak')
function showToast(title: string, description?: string, tone: 'success' | 'info' | 'danger' = 'success') { toast.value = { title, description, tone }; window.setTimeout(() => { toast.value = null }, 4000) }
function validateProfile() { const schema = z.object({ fullName: z.string().trim().min(1, t('validation.required')), email: z.string().email(t('validation.email')), phone: z.string().regex(/^\+?[0-9\s-]{8,20}$/, t('settings.profile.validation.phone')) }); const result = schema.safeParse(draft.profile); errors.value = {}; if (!result.success) result.error.issues.forEach((issue) => { errors.value[String(issue.path[0])] ??= issue.message }); return result.success }
async function saveChanges() { if (active.value === 'profile' && !validateProfile()) return; saving.value = true; await new Promise((resolve) => window.setTimeout(resolve, 450)); store.save(cloneSettings(draft)); baseline.value = JSON.stringify(store.settings); saving.value = false; showToast(t(active.value === 'profile' ? 'settings.profile.saved' : 'settings.toast.saved')) }
function cancelChanges() { Object.assign(draft, cloneSettings(store.settings)); errors.value = {} }
function resetPreferences() { Object.assign(draft.preferences, { ...defaultPreferences, language: store.language }); resetOpen.value = false }
function changePhoto(event: Event) { const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { draft.profile.photo = String(reader.result) }; reader.readAsDataURL(file) }
function changePassword() { const result = z.object({ current: z.string().min(1), next: z.string().min(8), confirm: z.string() }).refine((value) => value.next === value.confirm, { path: ['confirm'] }).safeParse(password); if (!result.success) { passwordError.value = t(password.next.length < 8 ? 'validation.passwordMin' : 'validation.passwordMatch'); return } passwordError.value = ''; Object.assign(password, { current: '', next: '', confirm: '' }); showToast(t('settings.security.passwordChanged')) }
function beforeUnload(event: BeforeUnloadEvent) { if (!dirty.value) return; event.preventDefault(); event.returnValue = '' }
onMounted(() => window.addEventListener('beforeunload', beforeUnload)); onBeforeUnmount(() => window.removeEventListener('beforeunload', beforeUnload))
onBeforeRouteLeave(() => dirty.value ? window.confirm(t('settings.unsaved.leaveWarning')) : true)
watch(() => draft.preferences.language, (value) => store.applyLanguage(value))
</script>

<template><div class="@container"><header><div class="flex flex-wrap items-center gap-3"><h1 class="page-title">{{ t('settings.title') }}</h1><UiBadge v-if="dirty" tone="warning">{{ t('settings.unsaved.label') }}</UiBadge></div><p class="secondary-text mt-2">{{ t('settings.subtitle') }}</p></header>
  <div class="mt-8 grid gap-6 lg:grid-cols-[14rem_minmax(0,1fr)]"><nav class="-mx-1 flex gap-1 overflow-x-auto px-1 pb-2 lg:mx-0 lg:block lg:space-y-1 lg:overflow-visible lg:p-0" :aria-label="t('settings.navigation')"><button v-for="item in sections" :key="item.id" type="button" class="flex min-h-11 shrink-0 items-center gap-3 rounded-lg px-3 py-2 text-sm font-medium lg:w-full" :class="active === item.id ? 'bg-green-50 text-green-700' : 'text-slate-600 hover:bg-slate-50'" @click="active = item.id"><component :is="item.icon" :size="18" />{{ t(`settings.sections.${item.id}`) }}</button></nav>
    <main class="min-w-0">
      <UiCard v-if="active === 'profile'" :title="t('settings.profile.title')" :description="t('settings.profile.description')"><div class="mb-6 flex flex-wrap items-center gap-4"><div class="flex size-20 items-center justify-center overflow-hidden rounded-full bg-green-50 text-2xl font-semibold text-green-700"><img v-if="draft.profile.photo" :src="draft.profile.photo" class="size-full object-cover" alt="" /><span v-else>{{ draft.profile.fullName.slice(0, 2).toUpperCase() }}</span></div><div class="flex flex-wrap gap-2"><input ref="photoInput" type="file" accept="image/*" class="hidden" @change="changePhoto" /><UiButton variant="secondary" size="sm" @click="photoInput?.click()">{{ t('settings.profile.changePhoto') }}</UiButton><UiButton v-if="draft.profile.photo" variant="ghost" size="sm" @click="draft.profile.photo = ''">{{ t('settings.profile.removePhoto') }}</UiButton></div></div><div class="grid gap-4 sm:grid-cols-2"><UiInput v-model="draft.profile.fullName" :label="t('settings.profile.fullName')" :error="errors.fullName" /><UiInput v-model="draft.profile.email" :label="t('settings.profile.email')" type="email" :error="errors.email" /><UiInput v-model="draft.profile.phone" :label="t('settings.profile.phone')" type="tel" :error="errors.phone" /><UiInput :model-value="t(isOwner ? 'settings.roles.owner' : 'settings.roles.worker')" :label="t('settings.profile.role')" disabled /></div></UiCard>
      <UiCard v-else-if="active === 'preferences'" :title="t('settings.preferences.title')" :description="t('settings.preferences.description')"><div class="grid gap-5 sm:grid-cols-2"><UiSelect v-model="draft.preferences.language" :label="t('settings.preferences.language')" :options="languageOptions" /><UiSelect v-model="draft.preferences.dateFormat" :label="t('settings.preferences.dateFormat')" :options="dateOptions" /><div><p class="ui-label">{{ t('settings.preferences.numberFormat') }}</p><p class="mt-2 rounded-lg bg-slate-50 px-3 py-2 text-sm">{{ formatNumber(1250.5) }}</p></div><UiSelect v-model="draft.preferences.weightUnit" :label="t('settings.preferences.weightUnit')" :options="weightOptions" /><UiSelect v-model="draft.preferences.areaUnit" :label="t('settings.preferences.areaUnit')" :options="areaOptions" /><UiSelect v-model="draft.preferences.theme" :label="t('settings.preferences.theme')" :options="themeOptions" /></div><template #footer><UiButton variant="ghost" @click="resetOpen = true">{{ t('settings.actions.reset') }}</UiButton></template></UiCard>
      <UiCard v-else-if="active === 'farm' && isOwner" :title="t('settings.farm.title')" :description="t('settings.farm.description')"><div class="grid gap-5 sm:grid-cols-2"><UiSelect v-model="draft.farm.defaultFarmId" :label="t('settings.farm.defaultFarm')" :options="farmOptions" /><UiSelect v-model="draft.farm.defaultVariety" :label="t('settings.farm.defaultVariety')" :options="varietyOptions" /><UiInput v-model="draft.farm.lowStockThresholdKg" :label="t('settings.farm.lowStock')" type="number" min="0" /></div><div class="mt-7 border-t border-slate-200 pt-6"><h3 class="font-semibold">{{ t('settings.farm.grades') }}</h3><div class="mt-4 space-y-5"><fieldset v-for="grade in draft.farm.grades" :key="grade.id" class="rounded-lg border border-slate-200 p-4"><legend class="px-2 font-medium">{{ t(`settings.farm.gradeNames.${grade.id}`) }}</legend><div class="grid gap-4 sm:grid-cols-2"><div><label class="ui-label">{{ t('common.indonesia') }}</label><textarea v-model="grade.descriptionId" class="ui-field mt-1.5 min-h-20" /></div><div><label class="ui-label">{{ t('common.english') }}</label><textarea v-model="grade.descriptionEn" class="ui-field mt-1.5 min-h-20" /></div></div></fieldset></div></div></UiCard>
      <UiCard v-else-if="active === 'sales' && isOwner" :title="t('settings.sales.title')" :description="t('settings.sales.description')"><div class="grid gap-5 sm:grid-cols-2"><UiInput :model-value="t('settings.sales.idr')" :label="t('settings.sales.currency')" disabled /><UiSelect v-model="draft.sales.defaultPaymentMethod" :label="t('settings.sales.paymentMethod')" :options="paymentMethodOptions" /><UiSelect v-model="draft.sales.defaultPaymentStatus" :label="t('settings.sales.paymentStatus')" :options="paymentStatusOptions" /><UiSelect v-model="draft.sales.defaultDeliveryMethod" :label="t('settings.sales.deliveryMethod')" :options="deliveryOptions" /><UiInput v-model="draft.sales.invoicePrefix" :label="t('settings.sales.invoicePrefix')" /><div><p class="ui-label">{{ t('settings.sales.invoicePreview') }}</p><p class="mt-2 rounded-lg bg-green-50 px-3 py-2 font-medium text-green-800">{{ invoicePreview }}</p></div></div><div class="mt-6 grid gap-4 sm:grid-cols-2"><div><label class="ui-label">{{ t('settings.sales.notesId') }}</label><textarea v-model="draft.sales.defaultInvoiceNotesId" class="ui-field mt-1.5 min-h-24" /></div><div><label class="ui-label">{{ t('settings.sales.notesEn') }}</label><textarea v-model="draft.sales.defaultInvoiceNotesEn" class="ui-field mt-1.5 min-h-24" /></div></div></UiCard>
      <UiCard v-else-if="active === 'notifications'" :title="t('settings.notifications.title')" :description="t('settings.notifications.description')"><div class="divide-y divide-slate-200"><section v-for="group in notificationGroups" :key="group.id" class="py-5 first:pt-0 last:pb-0"><h3 class="font-semibold">{{ t(`settings.notifications.groups.${group.id}`) }}</h3><div class="mt-3 space-y-3"><label v-for="key in group.items" :key="key" class="flex cursor-pointer items-center justify-between gap-4 rounded-lg px-2 py-2 hover:bg-slate-50"><span class="text-sm text-slate-700">{{ t(`settings.notifications.items.${key}`) }}</span><input v-model="draft.notifications[key]" type="checkbox" class="size-5 accent-green-700" /></label></div></section></div></UiCard>
      <UiCard v-else :title="t('settings.security.title')" :description="t('settings.security.description')"><section><h3 class="font-semibold">{{ t('settings.security.changePassword') }}</h3><div class="mt-4 grid gap-4 sm:grid-cols-2"><UiInput v-model="password.current" :label="t('settings.security.currentPassword')" :type="showCurrent ? 'text' : 'password'"><template #trailing><button type="button" class="p-2" @click="showCurrent = !showCurrent"><EyeOff v-if="showCurrent" :size="17" /><Eye v-else :size="17" /></button></template></UiInput><div></div><UiInput v-model="password.next" :label="t('settings.security.newPassword')" :type="showNext ? 'text' : 'password'"><template #trailing><button type="button" class="p-2" @click="showNext = !showNext"><EyeOff v-if="showNext" :size="17" /><Eye v-else :size="17" /></button></template></UiInput><UiInput v-model="password.confirm" :label="t('settings.security.confirmPassword')" :type="showConfirm ? 'text' : 'password'"><template #trailing><button type="button" class="p-2" @click="showConfirm = !showConfirm"><EyeOff v-if="showConfirm" :size="17" /><Eye v-else :size="17" /></button></template></UiInput></div><div class="mt-3 h-1.5 overflow-hidden rounded bg-slate-100"><div class="h-full" :class="passwordStrength === 'strong' ? 'w-full bg-green-600' : passwordStrength === 'medium' ? 'w-2/3 bg-amber-500' : 'w-1/3 bg-red-500'" /></div><p class="mt-1 text-xs text-slate-500">{{ t(`settings.security.strength.${passwordStrength}`) }}</p><p v-if="passwordError" class="mt-2 text-sm text-red-700">{{ passwordError }}</p><UiButton class="mt-4" @click="changePassword">{{ t('settings.security.changePassword') }}</UiButton></section><section class="mt-8 border-t border-slate-200 pt-6"><h3 class="font-semibold">{{ t('settings.security.session') }}</h3><dl class="mt-4 grid gap-4 sm:grid-cols-3"><div><dt class="ui-label">{{ t('settings.security.device') }}</dt><dd class="mt-1">Windows</dd></div><div><dt class="ui-label">{{ t('settings.security.browser') }}</dt><dd class="mt-1">Chrome</dd></div><div><dt class="ui-label">{{ t('settings.security.lastActive') }}</dt><dd class="mt-1 text-green-700">{{ t('settings.security.activeNow') }}</dd></div></dl><UiButton variant="danger" class="mt-5" @click="logoutOpen = true">{{ t('settings.security.logout') }}</UiButton></section></UiCard>
      <div v-if="active !== 'security'" class="mt-5 flex flex-wrap justify-end gap-3"><UiButton variant="secondary" :disabled="!dirty || saving" @click="cancelChanges">{{ t('common.cancel') }}</UiButton><UiButton :disabled="!dirty" :loading="saving" @click="saveChanges"><template #leading><Save :size="17" /></template>{{ t('settings.actions.save') }}</UiButton></div>
    </main></div>
  <UiModal v-model="resetOpen" :title="t('settings.reset.title')" :description="t('settings.reset.description')"><template #footer><UiButton variant="secondary" @click="resetOpen = false">{{ t('common.cancel') }}</UiButton><UiButton @click="resetPreferences">{{ t('settings.actions.reset') }}</UiButton></template></UiModal>
  <UiModal v-model="logoutOpen" :title="t('settings.security.logoutTitle')" :description="t('settings.security.logoutDescription')"><template #footer><UiButton variant="secondary" @click="logoutOpen = false">{{ t('common.cancel') }}</UiButton><UiButton variant="danger" @click="auth.logout(); router.replace('/login')">{{ t('settings.security.logout') }}</UiButton></template></UiModal>
  <div v-if="toast" class="fixed right-4 bottom-4 z-50"><UiToast v-bind="toast" @dismiss="toast = null" /></div>
</div></template>
